name: Running Tests
on: push

jobs:
  build:

    name: Build, get deps, and run unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: "Creating Generator"
      run: |
        cd devto_api
        mix deps.get
        echo "Deps installed.."
        mix test
        echo "Mix test"
